config/routes.rb
Nevernote::Application.routes.draw do
  # API routes. Backbone plugs in here.
  namespace 'api', defaults: {format: :json} do
    resource :user, only: [:show, :update]
    resources :notebooks, except: [:new, :edit]
    resources :tags, except: [:new, :edit]
    resources :notes, except: [:new, :edit] do
      resources :taggings, only: [:index, :create, :destroy]
    end
  end

  # Non-API, non-Backbone routes.
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resource :home, only: [:show]
  resource :about, only: [:show]

  root to: "landing#show"
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :title, :content, :url, :notebook_id

  validates :notebook_id, presence: true

  belongs_to(
    :notebook,
    class_name: "Notebook",
    foreign_key: :notebook_id,
    primary_key: :id
  )

  has_many(
    :taggings,
    class_name: "Tagging",
    foreign_key: :note_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :tags, 
    through: :taggings, 
    source: :tag
  )

  has_one(
    :owner,
    through: :notebook,
    source: :owner
  )
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  attr_accessible :name, :user_id, :default

  validates :name, :user_id, presence: true
  validates :name, uniqueness: { scope: :user_id }

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :notes,
    class_name: "Note",
    foreign_key: :notebook_id,
    primary_key: :id,
    dependent: :destroy
  )

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :user_id

  validates :name, :user_id, presence: true
  validates :name, uniqueness: { scope: :user_id }

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :taggings,
    class_name: "Tagging",
    foreign_key: :tag_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :notes,
    through: :taggings,
    source: :note
  )
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  attr_accessible :note_id, :tag_id

  validates :note_id, :tag_id, presence: true
  validates :note_id, uniqueness: { scope: :tag_id }

  belongs_to(
    :note,
    class_name: "Note",
    foreign_key: :note_id,
    primary_key: :id
  )

  belongs_to(
    :tag,
    class_name: "Tag",
    foreign_key: :tag_id,
    primary_key: :id
  )

  has_one(
    :owner, 
    through: :note, 
    source: :owner
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :notebook_id
  attr_reader :password

  validates :email, :username, :session_token, presence: true
  validates :password, length: { within: 6..64, allow_nil: true }
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :email, email: true
  validates :username, username: true
  validates :email, :username, :session_token, uniqueness: true

  before_validation :ensure_session_token

  belongs_to(
    :default_notebook,
    class_name: "Notebook",
    foreign_key: :notebook_id,
    primary_key: :id
  )

  has_many(
    :notebooks,
    class_name: "Notebook",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :tags,
    class_name: "Tag",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :notes, 
    through: :notebooks, 
    source: :notes
  )

  def self.find_by_credentials(email_or_username, password)
    if email_or_username.include?('@')
      user = User.find_by_email(email_or_username)
    else
      user = User.find_by_username(email_or_username)
    end

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  skip_before_filter :require_logged_in

  def show
    render :show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_filter :require_logged_in

  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    render :show
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  skip_before_filter :require_logged_in
  before_filter :require_logged_out

  def show
    render :show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :require_logged_in,  only: [:new, :create]
  before_filter :require_logged_out, only: [:new, :create]

  def new
    render :new
  end

  def create
    email_or_username = params[:email_or_username ]
    password = params[:password]
    user = User.find_by_credentials(email_or_username , password)

    if user.nil?
      render json: "Incorrect username and/or password."
    else
      login!(user)
      redirect_to home_url
    end
  end

  def destroy
    logout!(current_user)
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  skip_before_filter :require_logged_in,  only: [:new, :create]
  before_filter :require_logged_out, only: [:new, :create]

  def new
    render :new
  end

  def create
    user = User.new(params[:user])

    if user.save
      create_first_notebook!(user)
      login!(user)
      redirect_to home_url
    else
      render json: user.errors.full_messages
    end
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/api/tags_helper.rb
module Api::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logout!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def require_logged_in
    redirect_to new_session_url if current_user.nil?
  end

  def require_logged_out
    redirect_to home_url unless current_user.nil?
  end

  def require_ownership(model, id = params[:id])
    object = model.constantize.find(id)

    unless object.owner == current_user
      render json: "Can only edit your own #{model.pluralize}"
    end
  end

end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def create_first_notebook!(user)
    notebook_name = "#{user.username}'s notebook"
    notebook = Notebook.create(name: notebook_name, user_id: user.id)
    user.update_attributes(notebook_id: notebook.id)
  end

  def reset_default_notebook!(user)
    user.update_attributes(notebook_id: user.notebooks.first.id)
  end

  def change_default_notebook!(user, notebook)
    user.update_attributes(notebook_id: notebook.id)
  end

end

app/views/abouts/show.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "about" %>
<% end %>

<% content_for :body do %>
<header class="header group">
    <a href="<%= new_session_url %>" class="logo">
        <div class="logo-image">
            <img src="https://www.evernote.com/redesign/global/img/evernote-logo.png">
        </div>
        <h1 class="logo-text">
        Nevernote
        </h1>
    </a>
</header>
<section class="main group">
    <header>
        <h1>About this App</h1>
    </header>
    <div class="about-content">
      <p>
      Nevernote is a reproduction of the popular note-taking app
      <a href="http://www.evernote.com">Evernote</a>. It was built by Nick
      Willett-Jeffries in 2013 as his final project for App Academy. The app
      relies upon a number of key technologies including:
      </p>
      <ul>
        <li>Ruby on Rails</li>
        <li>Backbone.js</li>
        <li>PostgreSQL</li>
      </ul>

      <p>
      More information about Nick is available at
      <a href="http://nwj.cc">nwj.cc</a>.
      </p>
    </div>
</section>
<footer class="footer">
    <nav>
        <ul class="group">
            <li><a href="/about">About</a></li>
            <li>Built by NWJ 2013.</li>
        </ul>
    </nav>
</footer>
<% end %>

app/views/homes/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag('home') %>
<% end %>

<% content_for :body do %>
  <header class="header group">
    <div class="account-button group">
      <img src="http://www.evernote.com/redesign/global/img/badge-free.png">
      <h3><%= current_user.username %></h3>
      <img class="dropdown-arrow" src="https://www.evernote.com/redesign/global/img/menu-dropdown-arrow-white.png">
      <ul class="account-menu hide">
        <li>
          <a class="group" href="/about">
            <img src="https://www.evernote.com/redesign/global/img/icon-help.png">
            <h3>About</h3>
          </a>
        </li>
        <li>
          <a class="group" href="<%= session_url %>" data-method="delete" rel="no-follow">
            <img src="https://www.evernote.com/redesign/global/img/icon-logout.png">
            <h3>Log Out</h3>
          </a>
        </li>
      </ul>
    </div>
  </header>

  <div id="content" class="group">
  </div>

  <script>
    $(document).ready(function() {
      //Click handler for account menu
      $('.account-button').click(function(event) {
        $('.account-button').toggleClass('on');
        $('.account-menu').toggleClass('hide');
      })

      //Backbone initialization
      Nevernote.initialize();
    });
  </script>
<% end %>

app/views/landing/show.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag('landing') %>
<% end %>

<% content_for :body do %>
<header class="header group">
    <a href="<%= root_url %>" class="logo group">
        <img class="logo-image" src="https://www.evernote.com/redesign/global/img/elephant.png">
        <h1 class="logo-text">Nevernote</h1>
    </a>
    <div class="start-actions group">
        <ul>
            <li><a href="<%= new_session_url %>">Sign In</a></li>
            <li><a href="<%= new_user_url %>">Sign Up</a></li>
        </ul>
    </div>
</header>
<section class="banner">
    <div class="banner-copy">
        <h1>Remember Everything</h1>
        <p>
            Nevernote makes modern life manageable, by letting you easily collect and find everything that matters.
        </p>
        <form action="<%= session_url %>" method="post">
            <input
                type="hidden"
                name="authenticity_token"
                value="<%= form_authenticity_token %>"
            >
            <input type="hidden" name="email_or_username" value="Jane">
            <input type="hidden" name="password" value="password">
            <input id="demo" type="submit" value="Try the Demo">
        </form>
    </div>
    <img id="book" src="http://evernote.com/media/img/homepage-redesign/main-image/travel-books.png">
    <img id="pen" src="http://evernote.com/media/img/homepage-redesign/main-image/travel-pen.png">
    <img id="mac" src="http://evernote.com/media/img/homepage-redesign/main-image/travel-mac.png">
    <img id="phone" src="http://evernote.com/media/img/homepage-redesign/main-image/travel-iphone.png">
    <img id="wallet" src="http://evernote.com/media/img/homepage-redesign/main-image/travel-wallet.png">
</section>
<% end %>